- hosts: webserver
  become: yes
  tasks:
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Install Node.js and NPM
      yum:
        name: "nodejs"
        state: present
        enablerepo: "epel"
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    - name: Clean up the destination directory if it exists
      file:
        path: /var/www/node-app
        state: absent
    - name: Clone the Node.js application repository
      git:
        repo: 'https://github.com/ishankush01/Node-app'
        dest: /var/www/node-app

    - name: Install application dependencies
      command: npm install
      args:
        chdir: /var/www/node-app

    - name: Configure Nginx for the Node.js application
      copy:
        content: |
          server {
              listen 80;

              server_name _;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
        dest: /etc/nginx/conf.d/node-app.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Start the Node.js application
      command: npm start
      args:
        chdir: /var/www/node-app